<?php
/**
 * @file
 * Random functions that don't go elsewhere
 */


/**
 * Implements hook_entity_info_alter().
 */
function vvsq_misc_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['event_teaser'] = array(
    'label' => t('Event teaser'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function vvsq_misc_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'event_teaser') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__' . $vars['view_mode'];
  }
}
