; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[addtoany][version] = "4.4"

projects[admin_menu][version] = "3.0-rc4"

projects[advanced_help][version] = "1.0"

projects[advanced_forum][version] = "2.3"

projects[captcha][version] = "1.0"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[colorbox][version] = "2.4"

projects[context][version] = "3.0-beta7"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[email][version] = "1.2"

projects[entity][version] = "1.2"
projects[entity][patch] = "https://drupal.org/files/php5.5_bitwise_operator_fix-2050775-7_0.patch"

projects[features][version] = "1.0"

projects[imageapi][version] = "1.x-dev"

projects[imce][version] = "1.7"

projects[jquery_plugin][version] = "1.0"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[metatag][version] = "1.0-beta7"

projects[module_filter][version] = "1.8"

projects[mollom][version] = "2.7"

projects[pathauto][version] = "1.2"

projects[registration_role][version] = "7.1"

projects[rules][version] = "2.3"

projects[site_map][version] = "1.0"

projects[stage_file_proxy][version] = "1.4"

projects[strongarm][version] = "2.0"

projects[ubercart][version] = "3.5"

projects[token][version] = "1.5"

projects[token_filter][version] = "1.1"

projects[views][version] = "3.7"

projects[views_slideshow][version] = "3.0"
projects[views_slideshow][patch][] = "https://drupal.org/files/1872616-remove-deprecated-preg_replace-7.x-3.0.patch"

projects[webform][version] = "3.19"

projects[workbench][version] = "1.2"

projects[xmlsitemap][version] = "2.0-rc2"

; Themes
projects[zen][version] = "5.4"


; Libraries
; ---------
libraries[jquery][download][type] = "file"
libraries[jquery][download][url] = "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"

libraries[jqueryui][download][type] = "file"
libraries[jqueryui][download][url] = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"

libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%204.0.1%20for%20Drupal/ckeditor_4.0.1_for_drupal_7.zip"
