; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[addtoany][version] = "4"

projects[admin_menu][version] = "3"

projects[advanced_help][version] = "1"

projects[advanced_forum][version] = "2"

projects[captcha][version] = "1"

projects[ctools][version] = "1"

projects[ckeditor][version] = "1"

projects[ckeditor_link][version] = "2"

projects[colorbox][version] = "2"

projects[context][version] = "3"

projects[custom_breadcrumbs][version] = "2"

projects[date][version] = "2"

projects[devel][version] = "1"

projects[email][version] = "1"

projects[entity][version] = "1"
projects[entity][patch] = "https://drupal.org/files/php5.5_bitwise_operator_fix-2050775-7_0.patch"

projects[features][version] = "1"

projects[fivestar][version] = "2"

projects[imageapi][version] = "1"

projects[imce][version] = "1"

projects[jquery_plugin][version] = "1"

projects[jquery_update][version] = "2"

projects[link][version] = "1"

projects[libraries][version] = "2"

projects[metatag][version] = "1"

projects[module_filter][version] = "1"

projects[mollom][version] = "2"

projects[pathauto][version] = "1"

projects[registration_role][version] = "7"

projects[rules][version] = "2"

projects[site_map][version] = "1"

projects[stage_file_proxy][version] = "1"

projects[strongarm][version] = "2"

projects[ubercart][version] = "3"

projects[token][version] = "1"

projects[token_filter][version] = "1"

projects[views][version] = "3"

projects[views_slideshow][version] = "3"
projects[views_slideshow][patch][] = "https://drupal.org/files/1872616-remove-deprecated-preg_replace-7.x-3.0.patch"

projects[votingapi][version] = "2"

projects[webform][version] = "3"

projects[workbench][version] = "1"

projects[xmlsitemap][version] = "2"


; Libraries
; ---------
libraries[jquery][download][type] = "file"
libraries[jquery][download][url] = "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"

libraries[jqueryui][download][type] = "file"
libraries[jqueryui][download][url] = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"

libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%204.0.1%20for%20Drupal/ckeditor_4.0.1_for_drupal_7.zip"
